[package]
authors = ["Jacob Brown <kardeiz@gmail.com>"]
edition = "2018"
name = "oai"
version = "0.1.1"
license = "MIT"
description = "OAI harvester for Rust - more coming soon"

[dependencies]
bytes = "0.4.11"
chrono = { version = "0.4.6", features = ["serde"] }
failure = "0.1.3"
futures = "0.1.25"
reqwest = "0.9.5"
roxmltree = "0.3.0"
serde = "1.0.80"
serde-xml-rs = "0.2.1"
serde_derive = "1.0.80"
serde_json = "1.0.33"
serde_urlencoded = "0.5.4"
sxd-document = "0.3.0"
sxd-xpath = "0.4.2"
treexml = "0.7.0"
url = "1.7.2"
xmltree = "0.8.0"

[dev-dependencies]
tokio = "0.1.13"
